### ISSUE TITLE
sendEmails is failing

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#233]
There is an error in sendEmails
```text
ERROR] KeyError: 'new_user__password'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 38, in lambda_handler
    send_email(secrets=secrets, **json.loads(record["body"]))
  File "/var/task/lambda_function.py", line 67, in send_email
    raw_template, subject = templates[template_name]
```

Probably the issue in that lines inside databaseFunctions

```python
        #SEND THEM AN EMAIL TO SET THEIR PASSWORD
        _send_reset_password_email(
            data,
            cursor=cursor,
            connection=connection,
            email=payload["email"],
            template="new_user__password",
        )
```

**Comment by billypilgrim88** [comment]
Fixed.
