### ISSUE TITLE
Fix error with offers_history

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#236]
There is a field in `offers` which is not a part of `offers_history` that's why updateOffer is failing. Probably the problem is in `zoho_offer_id`
```text
[ERROR] SyntaxError: INSERT has more expressions than target columns
LINE 1: INSERT INTO offers_history (SELECT * FROM offers WHERE id = ...
                                           ^

Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 9065, in lambda_handler
    response = updateOffer(data, connection)
  File "/var/task/lambda_function.py", line 4636, in updateOffer
    cursor.execute(
  File "/var/task/psycopg2/extras.py", line 248, in execute
    return super(RealDictCursor, self).execute(query, vars)
```

**Comment by billypilgrim88** [comment]
Fixed
